---
name: Deploy AKS Cluster

on:
  push:
    branches:
      - main  # Set this to the branch you use for deployment
  workflow_dispatch:

jobs:
  setup-azure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Register Microsoft.Compute provider
        run: |
          status=$(az provider show --namespace Microsoft.Compute --query "registrationState" --output tsv)
          echo "Current status of Microsoft.Compute provider: $status"
          if [ "$status" != "Registered" ]; then
            az provider register --namespace Microsoft.Compute
            echo "Registration initiated..."
          else
            echo "Microsoft.Compute provider is already registered."
          fi

      - name: Check vCPU quota in France Central
        run: |
          az vm list-usage --location francecentral --query "[].{Type:localName, Total:limit, Used:currentValue}" --output table

      - name: Logout of Azure
        run: az logout

  build:
    needs: setup-azure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Make script executable
        run: chmod +x ./create-aks.sh

      - name: List files in the current directory
        run: ls -la

      - name: Run deployment script
        run: bash ./create-aks.sh

      - name: Logout of Azure
        run: az logout

  setup-aks-credentials:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group aks-github-grp --name aks-scripted-cluster --overwrite-existing
          kubectl config view

      - name: Logout of Azure
        run: az logout

  deploy-nginx:
    needs:  setup-aks-credentials
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group aks-github-grp --name aks-scripted-cluster --overwrite-existing
          kubectl config view

      - name: Create Nginx deployment
        run: |
          kubectl create deployment nginx --image=nginx

      - name: Expose the Nginx deployment as a LoadBalancer
        run: |
          kubectl expose deployment nginx --port=80 --type=LoadBalancer

      - name: Check the status of the service
        run: |
          kubectl get services

      - name: Scale Nginx deployment to 3 replicas
        run: |
          kubectl scale deployment nginx --replicas=3

      - name: Update Nginx image
        run: |
          kubectl set image deployment/nginx nginx=nginx:1.19.0

      - name: Logout of Azure
        run: az logout
